site:
  name: OTOLOG
  page_title: オトログ
  page_description: "OTOLOG(オトログ)は参加したライブを記録し、ライブの思い出を共有できるサービスです。"
  keywords: "OTOLOG, オトログ"
  message: 参加したライブを記録して<br>新しいライブと出会おう
  meta:
    ogp:
      type: "website"
fes_concerts_num: 5
